# Generated by Django 3.2.7 on 2021-10-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='logo',
            field=models.ImageField(default='Chip_2.jpg', null=True, upload_to=''),
        ),
    ]
