# Generated by Django 3.2.7 on 2021-10-15 12:24

from django.db import migrations, models
import validators


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200)),
                ('video', models.FileField(upload_to='video/%y', validators=[validators.file_size])),
            ],
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
