# Generated by Django 3.2.7 on 2021-10-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_project_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='body',
            field=models.CharField(max_length=200),
        ),
    ]
